name: Health check

#on:
#  schedule:
#    - cron: '0 18 * * 0'

jobs:
  healthcheck:
    runs-on: ubuntu-20.04
    steps:
      - name: Check health of deployed Pokedex
        uses: Jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-wild-surf-9721.fly.dev/health/