# fly.toml app configuration file generated for fullstack-blog-app-icy-rain-8861 on 2024-08-13T03:18:16+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fullstack-blog-app'
primary_region = 'arn'

[build]

[env]
  PORT = '3000'

[processes]
  app = 'node index.js'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
